site_name: "Documentation | Cover"
site_author: covercode.ooo
site_description: Cover is an open internet service for code verification on the Internet Computer, helping to reduce risk of malicious apps and canisters on the network.
site_url: https://docs.covercode.ooo/
copyright: '© 2021 Built by Fleek LLC'
repo_name: psychedelic/cover
repo_url: https://github.com/psychedelic/cover
theme:
  name: material
  custom_dir: overrides
  favicon: './imgs/favicon.ico'
  logo: './imgs/logo.png'
  font:
    text: 'Open Sans'
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/codehilite-theme.css'
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - meta
  - toc:
      permalink: true
nav:
  - Welcome to Cover ✅: index.md
  - <b>Overview</b> 🔎: "#"
  - What is Cover?: overview/what-is-cover.md
  - <b>Verifying Canister Code</b> ✅: "#"
  - Getting Started: integrate-cover/getting-started.md
  - Cover's GitHub Action: integrate-cover/getting-started.md/#github-action
  - <b>Query a Canister's Status</b> ❓: "#"
  - Checking Verification Status: check-status/getting-started.md
  - View Build History: check-status/getting-started.md/#build-history
  - <b>Repositories & Tools</b> 🧰: "#"
  - Cover Repo: "https://github.com/psychedelic/cover"
  - GitHub Action Repo: "https://github.com/psychedelic/cover"
  - <b>Resources</b> 📚:
    - The Internet Computer: "https://dfinity.org/faq"
    - Disclaimer: resources/disclaimer.md
    - Trademark: resources/trademark.md
    - Privacy: resources/privacy.md
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/psychedelic/cover/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cover_ooo
    - icon: fontawesome/brands/discord
      link: https://discord.gg/yVEcEzmrgm