site_name: "Documentation | CAP"
site_author: cap.ooo
site_description: CAP is an open internet service that provides an activity and transaction history all assets (Token/NFTs/etc...) on the Internet Computer can integrate to.
site_url: https://docs.cap.ooo/
copyright: '© 2021 Built by Fleek LLC'
repo_name: psychedelic/cap
repo_url: https://github.com/psychedelic/cap
theme:
  name: material
  custom_dir: overrides
  favicon: './imgs/favicon.ico'
  logo: './imgs/cap.png'
  font:
    text: 'Open Sans'
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/codehilite-theme.css'
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - meta
  - toc:
      permalink: true
nav:
  - Welcome to CAP 👋: index.md
  - <b>Overview</b> 👑: "#"
  - What is CAP?: overview/what-is-cap.md
  - <b>Integrate an NFT/Token</b> ⚡: "#"
  - CAP SDK - Getting Started: integrate-cap/getting-started.md
  - <b>Show CAP Data in UI/Apps</b> 📜: "#"
  - CAP JS - Getting Started: surface-data/getting-started.md
  - <b>Examples & Tools</b> 🧰: "#"
  - CAP Main Repo: "https://github.com/psychedelic/cap"
  - CAP SDK Repo: "https://github.com/Psychedelic/cap/tree/main/sdk"
  - CAP-js Repo: "https://github.com/psychedelic/cap-js"
  - <b>Resources</b> 📚:
    - The Internet Computer: "https://dfinity.org/faq"
    - Disclaimer: resources/disclaimer.md
    - Trademark: resources/trademark.md
    - Privacy: resources/privacy.md
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/psychedelic/cap/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cap_ois
    - icon: fontawesome/brands/discord
      link: https://discord.gg/yVEcEzmrgm